version: '3'
services:
  nextjs:
    build: ./
  nginx: 
    build: ./nginx
    ports:
      - 443:443
    volumes:
      - /etc/letsencrypt/live/bored-games.app:/etc/letsencrypt/live/bored-games.app/
